# Generated by Django 2.1.7 on 2019-04-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190412_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
