# Generated by Django 2.1.7 on 2019-04-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190402_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='question',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
